### ISSUE TITLE
When using [project.readme] it gets shifted to inside [project] and breaks pyproject.toml.

### ISSUE THREAD

**Issue by ocefpaf** [tox-dev/pyproject-fmt#110]
Sorry if I'm doing something wrong but when running the `pyproject-fmt` it breaks our pyproject.toml and moving it manually to below the "dynamic" entry fixes it.

One can see that in first commit of https://github.com/Unidata/netcdf4-python/pull/1267 in https://github.com/Unidata/netcdf4-python/pull/1267/commits/1872af61568a58807f221a435516573fc086e0f1.

Thanks for the awesome tool!

Feel free to close this if what I'm doing is out of scope for this tool.

**Comment by gaborbernat** [comment]
PR welcome to fix it.

**Comment by ocefpaf** [comment]
> PR welcome to fix it.

I'd be happy to if I understand first:

1. that it is really `pyproject-fmt`
2. how `pyproject-fmt` works :-)

**Comment by gaborbernat** [comment]
Yes to both.

**Comment by mj0nez** [comment]
Hey, I have tried to come up with a solution for this but think it’s actually an issue with the usage of the TOML-syntax. In their [docs](https://toml.io/en/v1.0.0#table) it’s emphasized, that you should not introduce sub-tables (e.g. ``[project.readme]``) after the top-level table (``[project]``). The reason is, that readme and another field of the same level are treated equally, even if their actual rendering might look different. So you could switch the order in your file and introduce all sub-tables (readme, scripts, urls…) beforehand like:

```Markdown
[project.readme]
text = '''netCDF version 4 has many features not found in earlier versions of the library...
'''
content-type = "text/x-rst"

[project]
name = "netcdf4"
description = "Provides an object-oriented python interface to the netCDF version 4 library"
dynamic = [
  "version",
]
```
This should not break your file.

**Comment by gaborbernat** [comment]
PR welcome 👍

**Comment by gaborbernat** [comment]
Done via https://github.com/tox-dev/pyproject-fmt/releases/tag/2.0.0
